name: word_wizard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/audios/
    - assets/images/
    - assets/
  uses-material-design: true
